from ds.stack.stack import Stack

s = Stack()
s.push(2)
s.push(3)
s.push(4)
print('stack', s)
print('popped', s.pop())
print('stack', s)
print('peeking, but not removing', s.peek())
print('stack', s)
print('popped', s.pop())
print('popped', s.pop())
print('popped', s.pop())
print('stack', s)
print('is empty?', s.isEmpty())
print('peeking, but not removing', s.peek())
s.push(4)
s.push(4)
s.push(4)
s.push(4)
s.push(4)
print('stack', s)
